version: '3'

tasks:
  start-db:
    desc: Run Postgres container
    cmds:
      - >
        docker container run --name special --rm
        -e POSTGRES_PASSWORD=eeteeZ0A
        -e POSTGRES_USER=special
        -e POSTGRES_DB=special
        -p 5433:5432
        -d postgres

  stop-db:
    desc: Stop Postgres container
    cmds:
      - docker container stop special

  start-app:
    desc: Start Spring Boot application
    cmds:
      - mvn spring-boot:run

  mvn-dependency-update:
    desc: Show Maven dependency updates
    cmds:
      - mvn versions:display-dependency-updates

  mvn-plugin-update:
    desc: Show Maven plugin updates
    cmds:
      - mvn versions:display-plugin-updates
